/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdad8",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#d3c3bf",
        "on-error": "#ffffff",
        "surface-dim": "#dbdad7",
        "on-error-container": "#93000a",
        "inverse-surface": "#30312f",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2df",
        "surface-tint": "#bf0229",
        "on-secondary-container": "#6e625f",
        "surface-container-lowest": "#ffffff",
        "bone-bg": "#FAF8F5",
        "inverse-primary": "#ffb3b1",
        "tertiary-fixed-dim": "#82d1ed",
        "on-surface": "#1b1c1a",
        "border-subtle": "rgba(26, 18, 16, 0.09)",
        "on-tertiary-fixed-variant": "#004e60",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#b6ebff",
        "charcoal-card": "#1A1210",
        "tertiary": "#005468",
        "background": "#fbf9f6",
        "primary": "#9e001f",
        "on-background": "#1b1c1a",
        "outline": "#906f6e",
        "on-tertiary-fixed": "#001f28",
        "error": "#ba1a1a",
        "surface-container-highest": "#e4e2df",
        "surface-container-high": "#eae8e5",
        "on-surface-variant": "#5c403f",
        "secondary-fixed": "#f0dfdb",
        "tertiary-container": "#006e87",
        "on-secondary-fixed": "#221a17",
        "primary-container": "#c8102e",
        "text-muted": "#737373",
        "secondary": "#685c59",
        "on-tertiary-container": "#b6ebff",
        "primary-fixed-dim": "#ffb3b1",
        "on-secondary-fixed-variant": "#4f4442",
        "inverse-on-surface": "#f2f0ed",
        "surface-bright": "#fbf9f6",
        "surface-container-low": "#f5f3f0",
        "surface-container": "#efeeeb",
        "on-primary-fixed": "#410007",
        "on-primary-container": "#ffdad8",
        "secondary-container": "#f0dfdb",
        "crimson-accent": "#C8102E",
        "on-primary-fixed-variant": "#92001c",
        "on-tertiary": "#ffffff",
        "outline-variant": "#e5bdbb",
        "surface": "#fbf9f6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "40px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "unit": "8px"
      },
      fontFamily: {
        "label-md": ["DM Sans"],
        "display-lg-mobile": ["DM Sans"],
        "body-lg": ["DM Sans"],
        "display-lg": ["DM Sans"],
        "display-xl": ["Instrument Serif", "serif"],
        "label-sm": ["DM Sans"],
        "headline-md": ["DM Sans"],
        "headline-lg": ["DM Sans"],
        "body-md": ["DM Sans"],
        "serif": ["Instrument Serif", "serif"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.03em", "fontWeight": "500"}],
        "display-xl": ["100px", {"lineHeight": "90px", "letterSpacing": "-0.04em", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.04em", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
